# Generated by Django 5.2.5 on 2025-09-09 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornavn', models.CharField(max_length=40)),
                ('etternavn', models.CharField(max_length=40)),
                ('adresse', models.CharField(max_length=100)),
                ('tlf_landskode', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Hund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=40)),
                ('rase', models.CharField(max_length=40)),
                ('eier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.eier')),
            ],
        ),
    ]
